// Post-build step: generate per-tool pre-rendered pages, Open Graph images,
// and the sitemap. Runs after `vite build` (see package.json "build").
//
// Why: the app is a client-side SPA, but social crawlers (Twitter, WhatsApp,
// Slack, Medium) and search engines read raw HTML. Serving a static page per
// tool — each with its own title/description/OG image — gives every tool URL
// (/tools/<id>) a unique, crawlable preview without any runtime server.
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync, copyFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';
import { TOOLS } from '../src/tools.data.js';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIST = join(ROOT, 'dist');
// PNG rendering is by far the slowest step (~90s for 206 images), and this
// script now runs on every build — including watch-mode rebuilds, which empty
// dist/ first. Cache rendered PNGs outside dist, keyed by the SVG content, so
// an unchanged tool is a file copy instead of a re-render.
const OG_CACHE = join(ROOT, 'node_modules', '.cache', 'zerog-og');
const SITE = 'https://zerog-toolbox.web.app';
const TODAY = new Date().toISOString().slice(0, 10);

const escAttr = (s) => String(s).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escXml = (s) => String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;');

// --- Per-tool <head> SEO block (replaces the TOOL-SEO marker region) ---
function seoBlock(tool) {
  const url = `${SITE}/tools/${tool.id}`;
  const img = `${SITE}/og/${tool.id}.png`;
  const title = `${tool.title} — ZeroG Toolbox`;
  const jsonLd = {
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: tool.title,
    url,
    description: tool.description,
    applicationCategory: 'UtilitiesApplication',
    operatingSystem: 'Any (modern web browser)',
    image: img,
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    isPartOf: { '@type': 'WebApplication', name: 'ZeroG Toolbox', url: `${SITE}/` },
  };
  return `<!-- TOOL-SEO:START (generated by scripts/postbuild.js) -->
    <meta name="description" content="${escAttr(tool.description)}" />
    <meta name="keywords" content="${escAttr((tool.keywords || []).join(', '))}" />
    <meta name="robots" content="index, follow" />
    <meta name="theme-color" content="#09090b" />
    <link rel="canonical" href="${url}" />

    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="ZeroG Toolbox" />
    <meta property="og:title" content="${escAttr(title)}" />
    <meta property="og:description" content="${escAttr(tool.description)}" />
    <meta property="og:url" content="${url}" />
    <meta property="og:image" content="${img}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escAttr(title)}" />
    <meta name="twitter:description" content="${escAttr(tool.description)}" />
    <meta name="twitter:image" content="${img}" />

    <script type="application/ld+json">
${JSON.stringify(jsonLd, null, 2)}
    </script>
    <!-- TOOL-SEO:END -->`;
}

// --- Open Graph image (1200x630 SVG -> PNG) ---
function wrap(text, maxChars) {
  const words = text.split(/\s+/);
  const lines = [];
  let line = '';
  for (const w of words) {
    if ((line + ' ' + w).trim().length > maxChars && line) {
      lines.push(line.trim());
      line = w;
    } else {
      line = (line + ' ' + w).trim();
    }
  }
  if (line) lines.push(line);
  return lines.slice(0, 3);
}

// Up to two initials from the first alphabetic words (e.g. "JSON Formatter
// & Validator" -> "JF"); always renders, unlike color emoji in resvg.
function monogram(title) {
  const words = title.split(/\s+/).filter((w) => /[A-Za-z0-9]/.test(w));
  return words.slice(0, 2).map((w) => w[0].toUpperCase()).join('');
}

function ogSvg(tool) {
  const lines = wrap(tool.title, 18);
  const tspans = lines
    .map((l, i) => `<tspan x="80" dy="${i === 0 ? 0 : 84}">${escXml(l)}</tspan>`)
    .join('');
  const titleY = 330 - (lines.length - 1) * 42;
  return `<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0" stop-color="#101018"/>
      <stop offset="1" stop-color="#09090b"/>
    </linearGradient>
    <radialGradient id="glow" cx="0.85" cy="0.1" r="0.7">
      <stop offset="0" stop-color="#7c3aed" stop-opacity="0.55"/>
      <stop offset="1" stop-color="#7c3aed" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="1200" height="630" fill="url(#bg)"/>
  <rect width="1200" height="630" fill="url(#glow)"/>
  <rect x="0" y="0" width="14" height="630" fill="#7c3aed"/>
  <rect x="74" y="74" width="150" height="150" rx="32" fill="#7c3aed" fill-opacity="0.18" stroke="#7c3aed" stroke-opacity="0.6" stroke-width="2"/>
  <text x="149" y="192" text-anchor="middle" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="92" fill="#c4b5fd">${escXml(monogram(tool.title))}</text>
  <text x="80" y="${titleY}" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="70" fill="#ffffff">${tspans}</text>
  <text x="80" y="540" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="28" fill="#a78bfa" letter-spacing="2">${escXml((tool.category || '').toUpperCase())} · 100% IN-BROWSER · NO UPLOADS</text>
  <text x="80" y="590" font-family="Helvetica, Arial, sans-serif" font-weight="700" font-size="34" fill="#ffffff">ZeroG Toolbox</text>
</svg>`;
}

function renderOg(tool, outPath) {
  mkdirSync(dirname(outPath), { recursive: true });
  const svg = ogSvg(tool);
  const hash = createHash('sha256').update(svg).digest('hex').slice(0, 12);
  const cached = join(OG_CACHE, `${tool.id}-${hash}.png`);
  if (!existsSync(cached)) {
    mkdirSync(OG_CACHE, { recursive: true });
    const resvg = new Resvg(svg, {
      fitTo: { mode: 'width', value: 1200 },
      font: { loadSystemFonts: true },
    });
    writeFileSync(cached, resvg.render().asPng());
  }
  copyFileSync(cached, outPath);
}

// --- Main ---
const indexHtml = readFileSync(join(DIST, 'index.html'), 'utf8');
const SEO_RE = /<!-- TOOL-SEO:START[\s\S]*?<!-- TOOL-SEO:END -->/;
const TITLE_RE = /<title>[\s\S]*?<\/title>/;
const MODULE_RE = /<script type="module"/;

if (!SEO_RE.test(indexHtml)) throw new Error('TOOL-SEO marker block not found in dist/index.html');
if (!TITLE_RE.test(indexHtml)) throw new Error('<title> not found in dist/index.html');
if (!MODULE_RE.test(indexHtml)) throw new Error('module <script> not found in dist/index.html');

mkdirSync(join(DIST, 'og'), { recursive: true });

for (const tool of TOOLS) {
  // 1. OG image
  renderOg(tool, join(DIST, 'og', `${tool.id}.png`));

  // 2. Pre-rendered page with tool-specific head + initial-tool marker
  const page = indexHtml
    .replace(TITLE_RE, `<title>${escXml(tool.title)} — ZeroG Toolbox</title>`)
    .replace(SEO_RE, seoBlock(tool))
    .replace(MODULE_RE, `<script>window.__INITIAL_TOOL__=${JSON.stringify(tool.id)}</script>\n    <script type="module"`);
  const dir = join(DIST, 'tools', tool.id);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, 'index.html'), page);
}

// 3. Sitemap (root + every tool URL)
const urls = [`${SITE}/`, ...TOOLS.map((t) => `${SITE}/tools/${t.id}`)];
const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls
  .map(
    (u) =>
      `  <url>\n    <loc>${u}</loc>\n    <lastmod>${TODAY}</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>${u.endsWith('/') ? '1.0' : '0.8'}</priority>\n  </url>`
  )
  .join('\n')}
</urlset>
`;
writeFileSync(join(DIST, 'sitemap.xml'), sitemap);
// Drop the stray copy of the static sitemap if Vite carried one over.
try { rmSync(join(DIST, 'public', 'sitemap.xml')); } catch {}

console.log(`postbuild: ${TOOLS.length} tool pages, ${TOOLS.length} OG images, sitemap with ${urls.length} URLs.`);
